s=input("Enter the string:")
lwr=s.lower()
n=lwr.split()
snake_case='_'.join(n)
upr=lwr.upper()
k=upr.split()
pascal_case=''.join(k)
print("The string in snake case is ",snake_case)
print("The string in pascal case is ",pascal_case)
